### ISSUE TITLE
Request to add to NC app page + docs

### ISSUE THREAD

**Issue by Rade0nFighter** [poulou0/nextcloud-homeassistant-integration#12]
Hello!

First of all massive thanks for this widget - super useful. Lots of HA->NC integrations but this is the only real option for NC->HC!

More of a UI/signposting suggestion than a bug - as a HA user rather than developer it took a fair bit of searching to figure out how to make the widget work - could I suggest updating the NC app page to reference the "Administration settings > "Home assistant integration" screen, and on that page, include the content from this comment: https://github.com/poulou0/nextcloud-

Specifically I think it would be beneficial to other users to include a help link (?) to the" Template widget" label of the "Home assitant integration" page in the NC admin settings indicating that the user should enable HA developer tools and then go to the Developer Tools > Templates page and copy/paste this template into the page on the NC admin area. From that point thy can customise thourh standar HA dev tools functionnality.

That is all ❤️

**Comment by poulou0** [comment]
Hey @Rade0nFighter 

Thank you for the kind words! Your message inspired me to spend some hours and I'm preparing a new version. :))

Do you mean updating [this page](https://apps.nextcloud.com/apps/integration_homeassistant) showing that it's configurable from the "Administration settings > "Home assistant integration"?
Which comment you are referring? The link to the comment is not complete.

Aren't HA dev tools enabled always?

Thanks for taking the time :100:

**Comment by poulou0** [comment]
I've created video tutorials and tried to show appropriate error messages in each step of the way. :)) hope it helps

**Comment by Rade0nFighter** [comment]
Hi @poulou0 yes that’s the one! I think you might be right about developer tools always being enabled, for some reason I had it in my ahead it was something needed to be enabled.

Turns out I can’t copy and paste 🙄 here’s the link i was referring to: https://github.com/poulou0/nextcloud-homeassistant-integration/issues/6#issuecomment-1694678145

Fantastic news about the new update and the YouTube video is super useful - thanks again for your work on this project, adding a HA widget for nextcloud is going to make a lot of fellow self-hosters very happy! 😊
