### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by davidlamkin** [poulou0/nextcloud-homeassistant-integration#2]
I am getting this error when trying to go to the "Home Assistant Integration" page in Admin settings:

[The page shows this]

> Internal Server Error
> The server was unable to complete your request.
> If this happens again, please send the technical details below to the server administrator.
> 
> More details can be found in the server log.
> Technical details
> 
> Remote Address: XX.XX.XX.XX
> Request ID: lGLoHogJKtfWNQqtOfqQ

My logs have this:

> [index] Error: Exception: template file not found: template:admin-settings at <<closure>>
> 
>  0. /config/www/nextcloud/lib/private/legacy/OC_Template.php line 151
>     OC\Template\TemplateFileLocator->find()
>  1. /config/www/nextcloud/lib/private/legacy/OC_Template.php line 88
>     OC_Template->findTemplate()
>  2. /config/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php line 207
>     OC_Template->__construct()
>  3. /config/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 130
>     OCP\AppFramework\Http\TemplateResponse->render()
>  4. /config/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php line 83
>     OCA\Settings\Controller\AdminSettingsController->formatSettings()
>  5. /config/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php line 149
>     OCA\Settings\Controller\AdminSettingsController->getSettings()
>  6. /config/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php line 68
>     OCA\Settings\Controller\AdminSettingsController->getIndexResponse()
>  7. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
>     OCA\Settings\Controller\AdminSettingsController->index()
>  8. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
>     OC\AppFramework\Http\Dispatcher->executeController()
>  9. /config/www/nextcloud/lib/private/AppFramework/App.php line 183
>     OC\AppFramework\Http\Dispatcher->dispatch()
> 10. /config/www/nextcloud/lib/private/Route/Router.php line 315
>     OC\AppFramework\App::main()
> 11. /config/www/nextcloud/lib/base.php line 1055
>     OC\Route\Router->match()
> 12. /config/www/nextcloud/index.php line 36
>     OC::handleRequest()
> 
> GET /settings/admin/integration_homeassistant

**Comment by poulou0** [comment]
Hey thank you for trying the app.

That's odd, it looks like the template file is not found.
I tested with the latest docker setups and it works normally.

I tried with a fresh docker production installation.
https://github.com/docker-library/docs/blob/master/nextcloud/README.md#using-the-apache-image
and with the nextcloud dev environment.
https://cloud.nextcloud.com/s/iyNGp8ryWxc7Efa?path=%2F1%20Setting%20up%20a%20development%20environment

Can you tell me me more about your installation?
Maybe we can narrow it down.

Can you see if the file "admin-settings.php" is under the "[root]/custom_apps/integration_homeassistant/templates"

**Comment by poulou0** [comment]
I just tried with the example that they give [here](https://hub.docker.com/r/linuxserver/nextcloud) and it works for me.
(indeed it's under `www/nextcloud/apps/integration_homeassistant/templates`)

![image](https://github.com/poulou0/nextcloud-homeassistant-integration/assets/48758557/13be8dcc-cabb-4fb8-95c1-60329cd247c1)

I assume that you use the latest versions of both Nextcloud (26.0.2 - Hub 4) and the plugin (0.0.2)

**Comment by poulou0** [comment]
I uploaded a new version, let me know if its fixed and if not I will reopen the issue again
