### ISSUE TITLE
Not able to install on Nextcloud AIO

### ISSUE THREAD

**Issue by maitpatni** [poulou0/nextcloud-homeassistant-integration#3]
Hi,

I am getting this error on a fresh installation of Nextcloud AIO

`Could not extract app integration_homeassistant: Unable to extract symbolic link {/mnt/ncdata/tmp/oc_tmp_JGMiAd-folder/integration_homeassistant/node_modules/@vueuse/components/node_modules/.bin/vue-demi-switch}`

Is there any fix for this?

Thanks.

**Comment by poulou0** [comment]
Hello, thanks for reporting it.
I will try AIO when i find the time.. The message is very straight forward, but at the same time it's under the a .bin/ folder which makes it very unfortunate to fail for something that shouldn't be there.. 🙈

Can you tell me a little bit more about your setup? like OS or anything else that can narrow it down..

**Comment by vague666** [comment]
I can say it installed fine for me on AIO 27 but I can't configure the widget. It shows only the spinning loading icon. 
`docker logs -f nextcloud-aio-mastercontainer` doesn't show any errors
![image](https://github.com/poulou0/nextcloud-homeassistant-integration/assets/8029742/8b757b59-f471-4929-ac62-ad0766580a97)

**Comment by poulou0** [comment]
This should be fixed now in the v0.0.4 I excluded the entire node_modules/ directory.
If not, let me know and I will reopen the issue
