### ISSUE TITLE
Doesn't allow for new lines

### ISSUE THREAD

**Issue by Casuallynoted** [poulou0/nextcloud-homeassistant-integration#4]
Attempting to add a line break/new line doesn't seem to work in the current version of the integration. All text gets clumped together.
![image](https://github.com/poulou0/nextcloud-homeassistant-integration/assets/6272557/8afdd8dd-664b-42e9-b523-809a2a9b8395)

**Comment by poulou0** [comment]
It takes html tags, you can try adding <br> or <br/>
👍
