### ISSUE TITLE
Class "OCA\HassIntegration\Controller\TemplateWidgetController" does not exist

### ISSUE THREAD

**Issue by ernstmosch** [poulou0/nextcloud-homeassistant-integration#5]
Hello Community

ive tried out the "Home Assistant integration"

after trying some things out i managed it to work.

But since the errormessages flood my nextcloud

like:

```
[index] Fehler: OC\AppFramework\Utility\QueryNotFoundException: Could not resolve OCA\HassIntegration\Controller\TemplateWidgetController! Class "OCA\HassIntegration\Controller\TemplateWidgetController" does not exist at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 142
   OC\AppFramework\Utility\SimpleContainer->resolve()
1. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 494
   OC\AppFramework\Utility\SimpleContainer->query()
2. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 466
   OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
3. /var/www/nextcloud/lib/private/AppFramework/App.php line 162
   OC\AppFramework\DependencyInjection\DIContainer->query()
4. /var/www/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
5. /var/www/nextcloud/lib/base.php line 1071
   OC\Route\Router->match()
6. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

GET /index.php/apps/integration_homeassistant/template-widget
from xxxxx by xxx at 2023-08-14T10:24:34+00:00
```

The Integration works.

if i put something like:

`{{ states('sensor.al2002120100299_state_of_charge', with_unit=True) }}`

in "template widget" it shows up.

Did i overread something in the instructions?

Please help. I assume that my content of the template widget doesnt meet the expectaitions but i have no hint in what way.

Greez Thomas

**Comment by poulou0** [comment]
Hello, I don't think you do anything wrong. I should find the time to fix it at some point :)

**Comment by poulou0** [comment]
@ernstmosch 
Just uploaded a new version but I had to delete the old releases.
So I'm not very sure if you will get it as an update, you can delete the app and re-install it.

Let me know if it works for you :))
