### ISSUE TITLE
config ? 

### ISSUE THREAD

**Issue by dl6dbh** [poulou0/nextcloud-homeassistant-integration#6]
The settings are still unclear to me

    Base Url is clear so far
    Long-lived access token ?  is that just the token generated by home assist or is there something else?
    Template widget what is entered here?

**Comment by poulou0** [comment]
The long lived token can be generated from your profile settings as described in the first minute of this video
https://youtu.be/p6v5ygpGZHg?si=A_5o5XfU2q7eoxq9

The template widget area gets HTML and jinja2 code.
You can find an example in your insurance under `Developer Tools > Template`
* https://jinja.palletsprojects.com/en/latest/templates/
* https://www.home-assistant.io/docs/configuration/templating/

If you are more of a video tutorial person:
* https://youtu.be/m1aqyX6LXlo?si=iTn5YkvtmM9EjUyf
* https://youtu.be/GnW0mLt2YLg?si=GInC7zNDXqGqWgGV

**Comment by dl6dbh** [comment]
Hallo poulou

thanks for the fast and goot answer.


I got a little further. The long-lived access token seems to work.
I was able to successfully get data from homeassist with wget in the shell.
Only with the template that doesn't seem to work yet. This is probably due to my lack of knowledge of jinja2.
I'm just missing Example to get a sensor displayed



Best

Meinolf

 

 

 

 


Gesendet: Sonntag, 27. August 2023 um 16:07 Uhr
Von: "Poulou" ***@***.***>
An: "poulou0/nextcloud-homeassistant-integration" ***@***.***>
Cc: "dl6dbh" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [poulou0/nextcloud-homeassistant-integration] config ? (Issue #6)


 

The long lived token can be generated from your profile settings as described in the first minute of this video
https://youtu.be/p6v5ygpGZHg?si=A_5o5XfU2q7eoxq9

The template widget area gets HTML and jinja2 code.
You can find an example in your insurance under Developer Tools > Template


	https://jinja.palletsprojects.com/en/latest/templates/
	https://www.home-assistant.io/docs/configuration/templating/


If you are more of a video tutorial person:


	https://youtu.be/m1aqyX6LXlo?si=iTn5YkvtmM9EjUyf
	https://youtu.be/GnW0mLt2YLg?si=GInC7zNDXqGqWgGV

**Comment by poulou0** [comment]
No problem, hope it helps, a simple example from my use case can be:
```html
Kitchen light: {{ states.switch.kitchen_light.state }}
```
A slightly fancier one:
```html
<div class="inlineblock">Kitchen light:</div>
<img src="/apps/user_status/img/user-status-{{ 'online' if is_state('switch.kitchen_light', 'on') else 'invisible' }}.svg" alt="kitchen light" style="vertical-align: middle" />
```

**Comment by dl6dbh** [comment]
thanks 

its is not running yet

see attachment . i dont now why

 

Meinolf

 

 
 

Gesendet: Sonntag, 27. August 2023 um 19:59 Uhr
Von: "Poulou" ***@***.***>
An: "poulou0/nextcloud-homeassistant-integration" ***@***.***>
Cc: "dl6dbh" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [poulou0/nextcloud-homeassistant-integration] config ? (Issue #6)


 

No problem, hope it helps, a simple example from my use case can be:


Kitchen light: {{ states.switch.kitchen_light.state }}


A slightly fancier one:


<div class="inlineblock">Kitchen light:</div>
<img src="/apps/user_status/img/user-status-{{ 'online' if is_state('switch.kitchen_light', 'on') else 'invisible' }}.svg" alt="kitchen light" style="vertical-align: middle" />

**Comment by poulou0** [comment]
Hi, i see that you reply via email.. your attachment didn't go through..

Try replying from a browser here
https://github.com/poulou0/nextcloud-homeassistant-integration/issues/6

**Comment by dl6dbh** [comment]
![home](https://github.com/poulou0/nextcloud-homeassistant-integration/assets/35333262/67ae25c8-4277-4ac7-86ef-970bba11039b)

**Comment by dl6dbh** [comment]
my momently config. any mistake in the syntax ?

**Comment by poulou0** [comment]
I don't see anything wrong on a first glance... try making a template in home assistant and then copy paste it in the nextcloud.

![image](https://github.com/poulou0/nextcloud-homeassistant-integration/assets/48758557/6cb8da22-0c06-43bc-8bad-5d322e7144ea)

**Comment by poulou0** [comment]
Hmm make sure that in your token there is no "new line character" `\n` (Enter) after the last part.

**Comment by poulou0** [comment]
Great thanks for telling!
I will include all this knowledge in the next release! :)

Cheers
