### ISSUE TITLE
incompatible with nc28

### ISSUE THREAD

**Issue by dl6dbh** [poulou0/nextcloud-homeassistant-integration#7]
hallo 
i runnnig the integration in nc27.xx well.
after update to nc28 it show incompatible with integration 
my by an trick or an new version of integration ?

**Comment by wolfspyre** [comment]
yeah, it looks like the plugin needs to be updated to support 28.... are there plans to do this anytime soon?

**Comment by poulou0** [comment]
Wow.. I didn't think anyone was using it, so I neglected it a little bit.. I will work on it soon, thanks for pointing out 👍

**Comment by poulou0** [comment]
@dl6dbh @wolfspyre
Just uploaded a new version but I had to delete the old releases.
So I'm not very sure if you will get it as an update, you can delete the app and re-install it.

Let me know if it works for you :))
