### ISSUE TITLE
Configuration issue with Nextcloud Hub 6 (27.1.4)

### ISSUE THREAD

**Issue by Fructose38** [poulou0/nextcloud-homeassistant-integration#8]
The app deployed correctly (or at least is activable), but the configuration returns an error  (Internal Error) 
![shot-2024-01-05_15-41-05](https://github.com/poulou0/nextcloud-homeassistant-integration/assets/63117225/0635b54c-77e7-44d2-82c6-5506bd5c5d85)
Logfile shows:
`{"reqId":"dPSkWTA6SiZ5mOC9xGTt","level":3,"time":"2024-01-05T14:39:52+00:00","remoteAddr":"192.168.1.42","user":"User","app":"index","method":"GET","url":"/index.php/settings/admin/integration_homeassistant","message":"Exception thrown: Exception","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.4.1","exception":{"Exception":"Exception","Message":"template file not found: template:admin-settings","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/OC_Template.php","line":151,"function":"find","class":"OC\\Template\\TemplateFileLocator","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/OC_Template.php","line":88,"function":"findTemplate","class":"OC_Template","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":207,"function":"__construct","class":"OC_Template","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":130,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":149,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/base.php","line":1068,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/share/webapps/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/share/webapps/nextcloud/lib/private/Template/TemplateFileLocator.php","Line":56,"CustomMessage":"Exception thrown: Exception"}}`

**Comment by poulou0** [comment]
Can you check that indeed the archive was extracted successfully in the apps directory?
It's a pretty big file, maybe during the update there was a timeout or something..

In my case its under the `/config/www/nextcloud/apps/integration_homeassistant/`
You should see all the files in this archive:
https://github.com/poulou0/nextcloud-homeassistant-integration/releases/download/v0.0.3/integration_homeassistant.tar.gz
_(especially the src/admin-settings.js file)_

**Comment by Fructose38** [comment]
Hello,
I can find a bunch of files extracted in "/var/lib/nextcloud/apps/integration_homeassistant/", and notably "js/admin-settings.js", yes.

**Comment by poulou0** [comment]
I pushed a new update that is significantly smaller, hopefully this is fixed now, I'm closing the issue but let me know if the problem insist and I will open it again
