### ISSUE TITLE
 LocalServerException Host violates local access rules Error during dashboard widget loading: OCA\HassIntegration\Dashboard\TemplateWidget 

### ISSUE THREAD

**Issue by freed40** [poulou0/nextcloud-homeassistant-integration#9]
![Screenshot 2024-01-05 at 17-13-06 Home assistant integration - Verwaltungseinstellungen - Nextcloud](https://github.com/poulou0/nextcloud-homeassistant-integration/assets/25461127/ef96bec4-0074-4fd5-bfde-402846a7bc10)

[no app in context] Fehler: Error during dashboard widget loading: OCA\HassIntegration\Dashboard\TemplateWidget	GET /ocs/v2.php/apps/dashboard/api/v2/widget-items?widgets%5B%5D=activity	von 192.168.xxx.xxx von *admin* um 05.01.2024, 16:57:18

**Comment by poulou0** [comment]
I believe its a duplicate with this one https://github.com/poulou0/nextcloud-homeassistant-integration/issues/10#issuecomment-1886128736

basically you can either
* use domain names with dots (like heimserver.local)
* or add a flag to the config (allow_local_remote_servers"

If not let me know and I can re-open the issue
